name: Publish
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and publish
        run: |
          git config --local user.name "johnny-mh"
          git config --local user.email "romz1212@gmail.com"
          npm install
          npm run build
          npx standard-version --no-verify
          git push --follow-tags origin HEAD --no-verify
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
