name: pull_request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Add dependencies for commitlint action
      run: echo "::set-env name=NODE_PATH::$GITHUB_WORKSPACE/node_modules"
    - uses: wagoid/commitlint-github-action@v1
    - name: test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
    - name: build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
