name: CI
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install, build and test
      run: |
        yarn install
        git log -1 --pretty=format:"%s" | yarn commitlint
        yarn build
        yarn test
