name: PR Build
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: |
        npm install
        git log -1 --pretty=format:"%s" | yarn commitlint
        npm run build
        npm test
